import { StyleSheet, Platform, Dimensions } from 'react-native';
import { C } from '../config/constants';

const { width } = Dimensions.get('window');

// ==================== STYLES ====================
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.background },
  premiumHeader: {
    paddingTop: Platform.OS === 'ios' ? 55 : 45,
    paddingBottom: 28,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    marginBottom: 20,
  },
  headerContent: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerGreeting: { fontSize: 13, color: 'rgba(255,255,255,0.8)', letterSpacing: 0.5 },
  headerName: { fontSize: 24, fontWeight: '800', color: C.white, marginTop: 4 },
  headerBadge: {
    backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 14,
    paddingVertical: 8, borderRadius: 25, flexDirection: 'row', alignItems: 'center', gap: 6,
  },
  headerBadgeText: { color: C.white, fontSize: 12, fontWeight: '600' },
  premiumCard: {
    backgroundColor: C.white, borderRadius: 24, padding: 18, marginBottom: 16,
    shadowColor: C.primary, shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06, shadowRadius: 16, elevation: 4,
    borderWidth: 1, borderColor: C.border,
  },
  statsRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, marginBottom: 24 },
  statCard: {
    flex: 1, backgroundColor: C.white, borderRadius: 20, padding: 14, alignItems: 'center',
    shadowColor: C.shadow, shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04, shadowRadius: 8, elevation: 2, borderWidth: 1, borderColor: C.border,
  },
  statValue: { fontSize: 24, fontWeight: '800', color: C.dark },
  statLabel: { fontSize: 11, color: C.gray, marginTop: 6 },
  sectionTitle: { fontSize: 16, fontWeight: '800', color: C.dark, marginBottom: 14, marginTop: 20, letterSpacing: 0.1 },
  classScroll: { marginBottom: 16 },
  classButtons: { flexDirection: 'row', gap: 12, flexWrap: 'wrap' },
  classButton: {
    paddingHorizontal: 20, paddingVertical: 10, borderRadius: 30,
    backgroundColor: C.white, borderWidth: 1, borderColor: C.border,
    shadowColor: C.shadow, shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04, shadowRadius: 4, elevation: 2,
  },
  classButtonActive: { backgroundColor: C.primary, borderColor: C.primary },
  classButtonText: { fontSize: 13, fontWeight: '600', color: C.gray },
  classButtonTextActive: { color: C.white },
  studentCard: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: C.white,
    borderRadius: 18, padding: 14, marginBottom: 12,
    borderWidth: 1, borderColor: C.border,
    shadowColor: C.shadow, shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04, shadowRadius: 6, elevation: 2,
  },
  studentCardSelected: { borderWidth: 2, borderColor: C.primary, backgroundColor: C.primaryBg },
  studentCardRegistered: { borderWidth: 2, borderColor: C.success, backgroundColor: C.successLight },
  studentAvatar: {
    width: 54, height: 54, borderRadius: 27, backgroundColor: C.primaryLight,
    alignItems: 'center', justifyContent: 'center', marginRight: 14,
  },
  avatarText: { fontSize: 22, fontWeight: '700', color: C.primary },
  studentInfo: { flex: 1 },
  studentName: { fontSize: 16, fontWeight: '700', color: C.dark },
  studentRoll: { fontSize: 12, color: C.gray, marginTop: 2 },
  badge: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 14 },
  badgeText: { fontSize: 10, fontWeight: '600' },
  registrationCard: {
    backgroundColor: C.white, borderRadius: 24, padding: 20, marginTop: 20,
    borderWidth: 2, borderColor: C.primary,
    shadowColor: C.primary, shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12, shadowRadius: 12, elevation: 6,
  },
  alreadyRegisteredCard: {
    backgroundColor: C.successLight, borderRadius: 24, padding: 20, marginTop: 20,
    borderWidth: 2, borderColor: C.success,
    shadowColor: C.success, shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12, shadowRadius: 12, elevation: 6,
  },
  premiumBtn: {
    borderRadius: 16, paddingVertical: 16, alignItems: 'center', justifyContent: 'center',
    shadowColor: C.primary, shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 8, elevation: 5,
  },
  premiumBtnText: { color: C.white, fontSize: 16, fontWeight: '700' },
  cameraModalContainer: {
    flex: 1, backgroundColor: '#000',
  },
  cameraOverlay: { flex: 1 },
  cameraHeader: {
    flexDirection: 'row', justifyContent: 'space-between', padding: 20,
    paddingTop: Platform.OS === 'ios' ? 55 : 35,
    zIndex: 10,
  },
  cameraButton: {
    backgroundColor: 'rgba(0,0,0,0.6)', paddingHorizontal: 20, paddingVertical: 10,
    borderRadius: 30, borderWidth: 1, borderColor: 'rgba(255,255,255,0.3)',
  },
  cameraButtonText: { color: C.white, fontSize: 14, fontWeight: '600' },
  cameraGuide: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  cameraOval: { width: 280, height: 320, borderWidth: 2.5, borderColor: 'rgba(255,255,255,0.9)', borderRadius: 140 },
  cameraGuideText: {
    color: C.white, fontSize: 14, marginTop: 20,
    backgroundColor: 'rgba(0,0,0,0.6)', paddingHorizontal: 18, paddingVertical: 10,
    borderRadius: 25, fontWeight: '500',
  },
  cameraCapture: { alignItems: 'center', paddingBottom: 40 },
  captureButton: {
    width: 84, height: 84, borderRadius: 42, backgroundColor: C.white,
    alignItems: 'center', justifyContent: 'center',
    shadowColor: '#000', shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 8, elevation: 8,
  },
  captureInner: { width: 74, height: 74, borderRadius: 37, backgroundColor: C.primary },
  toast: {
    position: 'absolute', top: 60, left: 20, right: 20, borderRadius: 14,
    padding: 16, zIndex: 1000, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    shadowColor: '#000', shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2, shadowRadius: 8, elevation: 10,
  },
  toastSuccess: { backgroundColor: C.success },
  toastError: { backgroundColor: C.error },
  toastWarning: { backgroundColor: C.warning },
  toastInfo: { backgroundColor: C.info },
  toastText: { color: C.white, fontSize: 14, fontWeight: '600', textAlign: 'center' },
  emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
  emptyIcon: { fontSize: 64, marginBottom: 16, opacity: 0.5 },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: C.dark, marginBottom: 8 },
  emptyMessage: { fontSize: 14, color: C.gray, textAlign: 'center' },
  periodCard: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: C.white,
    borderRadius: 18, padding: 16, marginBottom: 12,
    borderWidth: 1, borderColor: C.border,
    shadowColor: C.shadow, shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04, shadowRadius: 6, elevation: 2,
  },
  periodNumber: {
    width: 60, height: 60, borderRadius: 16, backgroundColor: C.primaryLight,
    alignItems: 'center', justifyContent: 'center', marginRight: 16,
  },
  periodNumberText: { fontSize: 22, fontWeight: '800', color: C.primary },
  periodInfo: { flex: 1 },
  periodSubject: { fontSize: 16, fontWeight: '600', color: C.dark },
  periodTime: { fontSize: 12, color: C.gray, marginTop: 4 },
  tabBar: {
    flexDirection: 'row', backgroundColor: C.white,
    paddingTop: 8, paddingBottom: Platform.OS === 'ios' ? 28 : 10,
    paddingHorizontal: 8, borderTopWidth: 1, borderTopColor: C.border,
    shadowColor: '#000', shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08, shadowRadius: 14, elevation: 14,
  },
  tabItem: { flex: 1, alignItems: 'center', paddingVertical: 2 },
  tabItemInner: {
    alignItems: 'center', paddingVertical: 7, paddingHorizontal: 14,
    borderRadius: 14, minWidth: 64,
  },
  tabItemInnerActive: { backgroundColor: C.primaryBg },
  tabIcon: { fontSize: 20, color: '#94A3B8' },
  tabIconActive: { color: C.primary },
  tabLabel: { fontSize: 10, color: '#94A3B8', fontWeight: '500', marginTop: 2 },
  tabLabelActive: { color: C.primary, fontWeight: '700' },
  loginCard: { backgroundColor: C.white, borderRadius: 32, padding: 32 },
  loginTitle: { fontSize: 28, fontWeight: 'bold', color: C.dark, textAlign: 'center', marginBottom: 8 },
  loginSubtitle: { fontSize: 14, color: C.gray, textAlign: 'center', marginBottom: 32 },
  inputContainer: { marginBottom: 20 },
  inputLabel: { fontSize: 13, fontWeight: '600', color: C.dark, marginBottom: 8, marginLeft: 4 },
  inputWrapper: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: C.lightGray,
    borderRadius: 16, borderWidth: 1, borderColor: C.border, paddingHorizontal: 16,
  },
  input: { flex: 1, paddingVertical: 16, fontSize: 15, color: C.dark },
  quickActionCard: {
    flex: 1, minWidth: '45%', backgroundColor: C.white, borderRadius: 20,
    padding: 18, alignItems: 'center', marginBottom: 12,
    shadowColor: C.shadow, shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06, shadowRadius: 8, elevation: 3,
    borderWidth: 1.5, borderColor: C.border,
  },
  quickActionIcon: { width: 60, height: 60, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  quickActionTitle: { fontSize: 13, fontWeight: '700', color: C.dark, textAlign: 'center', marginTop: 6 },
  quickActionSub: { fontSize: 11, color: C.gray, textAlign: 'center', marginTop: 3 },
  progressCard: {
    backgroundColor: C.white, borderRadius: 24, padding: 24, marginBottom: 20,
    shadowColor: C.shadow, shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08, shadowRadius: 12, elevation: 3,
  },
  progressHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  progressLabel: { fontSize: 14, fontWeight: '600', color: C.gray },
  progressPercentage: { fontSize: 32, fontWeight: '800' },
  progressBar: { height: 10, backgroundColor: C.lightGray, borderRadius: 6, overflow: 'hidden', marginBottom: 12 },
  progressFill: { height: '100%', borderRadius: 6 },
  progressMessage: { fontSize: 12, color: C.gray, textAlign: 'center', marginTop: 8 },
  attendanceStats: { flexDirection: 'row', gap: 10, marginBottom: 20 },
  attendanceStat: {
    flex: 1, backgroundColor: C.white, borderRadius: 16, padding: 14, alignItems: 'center',
    shadowColor: C.shadow, shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04, shadowRadius: 6, elevation: 2,
    borderWidth: 1, borderColor: C.border,
  },
  attendanceStatValue: { fontSize: 24, fontWeight: '800' },
  attendanceStatLabel: { fontSize: 11, color: C.gray, marginTop: 4 },
  checkbox: {
    width: 26, height: 26, borderRadius: 8, borderWidth: 2,
    borderColor: C.primary, alignItems: 'center', justifyContent: 'center', marginRight: 16,
  },
  checkboxChecked: { backgroundColor: C.primary },
  checkboxCheck: { color: '#fff', fontSize: 14, fontWeight: 'bold' },
  saveButton: {
    backgroundColor: C.primary, paddingVertical: 18, borderRadius: 18,
    alignItems: 'center', marginTop: 12,
    shadowColor: C.primary, shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 8, elevation: 5,
  },
  saveButtonText: { color: C.white, fontSize: 16, fontWeight: '700' },
  instructions: {
    marginTop: 20, padding: 18, backgroundColor: C.infoLight,
    borderRadius: 20, borderLeftWidth: 5, borderLeftColor: C.info,
  },
  instructionsTitle: { fontSize: 14, fontWeight: '700', color: C.info, marginBottom: 10 },
  instructionsText: { fontSize: 12, color: C.gray, marginBottom: 6 },
  stepIndicator: { flexDirection: 'row', alignItems: 'center', marginBottom: 28, paddingHorizontal: 10 },
  stepItem: { alignItems: 'center', flex: 1 },
  stepCircle: {
    width: 40, height: 40, borderRadius: 20, backgroundColor: C.border,
    alignItems: 'center', justifyContent: 'center',
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1, shadowRadius: 4, elevation: 2,
  },
  stepActive: { backgroundColor: C.primary },
  stepCompleted: { backgroundColor: C.success },
  stepNumber: { color: C.white, fontWeight: 'bold', fontSize: 16 },
  stepLabel: { fontSize: 11, marginTop: 8, color: C.gray, textAlign: 'center' },
  stepLabelActive: { color: C.primary, fontWeight: '600' },
  stepLine: { width: 50, height: 2, backgroundColor: C.border },
  stepLineActive: { backgroundColor: C.primary },
  scanningDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: C.error, marginRight: 6 },
  scanningBadge: {
    position: 'absolute', top: 16, right: 16,
    backgroundColor: 'rgba(239,68,68,0.92)', borderRadius: 30,
    paddingHorizontal: 16, paddingVertical: 8,
    flexDirection: 'row', alignItems: 'center', zIndex: 10,
  },
  detectedBanner: {
    position: 'absolute', bottom: 20, left: 16, right: 16,
    backgroundColor: C.success, borderRadius: 16, padding: 14, alignItems: 'center',
    shadowColor: '#000', shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 8, elevation: 8, zIndex: 10,
  },
  tabToggle: { flexDirection: 'row', backgroundColor: C.lightGray, borderRadius: 14, padding: 4, marginBottom: 16 },
  tabToggleBtn: { flex: 1, paddingVertical: 10, borderRadius: 10, alignItems: 'center' },
  tabToggleBtnActive: { backgroundColor: C.white, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 4, elevation: 2 },
  tabToggleText: { fontSize: 13, fontWeight: '600', color: C.gray },
  tabToggleTextActive: { color: C.primary },
  periodAttendCard: {
    backgroundColor: C.white, borderRadius: 16, padding: 14, marginBottom: 10,
    borderWidth: 1, borderColor: C.border,
    shadowColor: C.shadow, shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04, shadowRadius: 6, elevation: 2,
    flexDirection: 'row', alignItems: 'center',
  },
  periodBadge: {
    width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginRight: 12,
  },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  calendarDay: {
    width: (width - 80) / 7, height: (width - 80) / 7,
    borderRadius: 8, alignItems: 'center', justifyContent: 'center',
  },
  calendarDayText: { fontSize: 11, fontWeight: '600' },
  reportFilterBar: {
    flexDirection: 'row', gap: 12, marginBottom: 16, alignItems: 'center',
  },
  dateInput: {
    flex: 1, paddingHorizontal: 12, paddingVertical: 10,
    backgroundColor: C.white, borderRadius: 12, borderWidth: 1, borderColor: C.border,
    fontSize: 13,
  },
});

export default styles;
